In [20]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

ModuleNotFoundError: No module named 'kagglehub'

# import libraries

In [21]:
import numpy as np
import pandas as pd

In [22]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv'

In [4]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [9]:
import numpy as np
one_d = np.array([1,2,3,4])
two_d = np.array([[1,2,3,4],[5,6,7,8]])
three_d = np.array([[[1,2],[3,4],[5,6]],
                    [[1,2],[3,4],[5,6]],
                    [[1,2],[3,4],[5,6]]])
print(three_d.ndim)

four_d = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])

print(four_d.ndim)

3
4


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [ ]:
one_d = np.arange(1, 5).reshape(4)

two_d = np.arange(1, 9).reshape(2, 4)

three_d = np.arange(1, 13).reshape(2, 2, 3)

four_d = np.arange(1, 17).reshape(2, 2, 2, 2)

print(one_d)
print("-------")
print(two_d)
print("-------")

print(three_d)
print("-------")

print(four_d)

[1 2 3 4]
-------
[[1 2 3 4]
 [5 6 7 8]]
-------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
-------
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


# create array using ones and zeros

In [16]:

one_array =np.ones((3, 3))
print(one_array)

zeros_array =np.zeros((3, 3))
print(zeros_array)

# random_array = np.random.random((2, 3))
# print("Random array:")
# print(random_array)

# random_integer_array = np.random.randint(1, 11, size=(2, 3))
# print("Random integer array:")
# print(random_integer_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# using random

In [17]:
random_array = np.random.random((2, 3))
print(random_array)

[[0.81560392 0.10026319 0.70292973]
 [0.8943254  0.55571688 0.64893616]]


# using linspace

In [19]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# create 1D array of tip from tips dataframe

In [23]:
tip = tips["tip"].to_numpy()
print(tip)

NameError: name 'tips' is not defined

# create 2D array of tip and total_bill form tips dataframe

# practice atleast 2 example for each using ndim, shape, size and itemsize

# change data type and memory size of any np-array using astype()

# create 2 same dimensional array and do scalar and vector operations

# find minimun and maximum tip

# find average total_bill and average tip

# find median total_bill

# find standard deviasion and variance of tip

# find log values of tip

# apply round, floor and ceil operation on tip array

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

# stacking and spliting

In [5]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

# use hsplit() and vsplit()