<a href="https://www.kaggle.com/code/asad196/mlb-2-class-5-assignment-f1d455?scriptVersionId=347064889" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [ ]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

# import libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [ ]:
tips.head()

# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [4]:
import numpy as np
one_d = np.array([1,2,3,4])
two_d = np.array([[1,2,3,4],[5,6,7,8]])
three_d = np.array([[[1,2],[3,4],[5,6]],
                    [[1,2],[3,4],[5,6]],
                    [[1,2],[3,4],[5,6]]])
print(three_d.ndim)

four_d = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])

print(four_d.ndim)

3
4


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [5]:
one_d = np.arange(1, 5).reshape(4)

two_d = np.arange(1, 9).reshape(2, 4)

three_d = np.arange(1, 13).reshape(2, 2, 3)

four_d = np.arange(1, 17).reshape(2, 2, 2, 2)

print(one_d)
print("-------")
print(two_d)
print("-------")

print(three_d)
print("-------")

print(four_d)

[1 2 3 4]
-------
[[1 2 3 4]
 [5 6 7 8]]
-------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
-------
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


# create array using ones and zeros

In [6]:

one_array =np.ones((3, 3))
print(one_array)

zeros_array =np.zeros((3, 3))
print(zeros_array)

# random_array = np.random.random((2, 3))
# print("Random array:")
# print(random_array)

# random_integer_array = np.random.randint(1, 11, size=(2, 3))
# print("Random integer array:")
# print(random_integer_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# using random

In [7]:
random_array = np.random.random((2, 3))
print(random_array)

[[0.76966353 0.82308269 0.28028372]
 [0.40726625 0.28820414 0.54762065]]


# using linspace

In [8]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# create 1D array of tip from tips dataframe

In [9]:
tip = tips["tip"].to_numpy()
print(tip)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

# create 2D array of tip and total_bill form tips dataframe

In [10]:
tip_array = tips["tip"].to_numpy()
print(tip_array)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

In [11]:
tip_bill_array = tips[["tip", "total_bill"]].to_numpy()
print(tip_bill_array)

[[ 1.01 16.99]
 [ 1.66 10.34]
 [ 3.5  21.01]
 [ 3.31 23.68]
 [ 3.61 24.59]
 [ 4.71 25.29]
 [ 2.    8.77]
 [ 3.12 26.88]
 [ 1.96 15.04]
 [ 3.23 14.78]
 [ 1.71 10.27]
 [ 5.   35.26]
 [ 1.57 15.42]
 [ 3.   18.43]
 [ 3.02 14.83]
 [ 3.92 21.58]
 [ 1.67 10.33]
 [ 3.71 16.29]
 [ 3.5  16.97]
 [ 3.35 20.65]
 [ 4.08 17.92]
 [ 2.75 20.29]
 [ 2.23 15.77]
 [ 7.58 39.42]
 [ 3.18 19.82]
 [ 2.34 17.81]
 [ 2.   13.37]
 [ 2.   12.69]
 [ 4.3  21.7 ]
 [ 3.   19.65]
 [ 1.45  9.55]
 [ 2.5  18.35]
 [ 3.   15.06]
 [ 2.45 20.69]
 [ 3.27 17.78]
 [ 3.6  24.06]
 [ 2.   16.31]
 [ 3.07 16.93]
 [ 2.31 18.69]
 [ 5.   31.27]
 [ 2.24 16.04]
 [ 2.54 17.46]
 [ 3.06 13.94]
 [ 1.32  9.68]
 [ 5.6  30.4 ]
 [ 3.   18.29]
 [ 5.   22.23]
 [ 6.   32.4 ]
 [ 2.05 28.55]
 [ 3.   18.04]
 [ 2.5  12.54]
 [ 2.6  10.29]
 [ 5.2  34.81]
 [ 1.56  9.94]
 [ 4.34 25.56]
 [ 3.51 19.49]
 [ 3.   38.01]
 [ 1.5  26.41]
 [ 1.76 11.24]
 [ 6.73 48.27]
 [ 3.21 20.29]
 [ 2.   13.81]
 [ 1.98 11.02]
 [ 3.76 18.29]
 [ 2.64 17.59]
 [ 3.15 20.08]
 [ 2.47 16

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [ ]:
print("one_d ndim:", one_d.ndim)
print("two_d ndim:", two_d.ndim)

print("one_d shape:", one_d.shape)
print("two_d shape:", two_d.shape)

print("one_d size:", one_d.size)
print("two_d size:", two_d.size)

print("one_d itemsize:", one_d.itemsize)
print("two_d itemsize:", two_d.itemsize)

# change data type and memory size of any np-array using astype()

In [12]:
integer_array = np.array([1, 2, 3, 4], dtype=np.int64)
small_integer_array = integer_array.astype(np.int8)

print(integer_array)
print(integer_array.dtype, integer_array.itemsize)

print(small_integer_array)
print(small_integer_array.dtype, small_integer_array.itemsize)

[1 2 3 4]
int64 8
[1 2 3 4]
int8 1


# create 2 same dimensional array and do scalar and vector operations

In [13]:
array_a = np.array([1, 2, 3, 4])
array_b = np.array([5, 6, 7, 8])

print("Scalar addition:", array_a + 10)
print("Scalar multiplication:", array_a * 2)

print("Vector addition:", array_a + array_b)
print("Vector subtraction:", array_b - array_a)
print("Vector multiplication:", array_a * array_b)

Scalar addition: [11 12 13 14]
Scalar multiplication: [2 4 6 8]
Vector addition: [ 6  8 10 12]
Vector subtraction: [4 4 4 4]
Vector multiplication: [ 5 12 21 32]


# find minimun and maximum tip

In [27]:
print("Minimum tip:", tip_array.min())
print("Maximum tip:", tip_array.max())

Minimum tip: 1.0
Maximum tip: 10.0


# find average total_bill and average tip

In [26]:
print("Average total bill:", tips["total_bill"].mean())
print("Average tip:", tips["tip"].mean())

Average total bill: 19.78594262295082
Average tip: 2.99827868852459


# find median total_bill

In [25]:
print("Median total bill:", tips["total_bill"].median())

Median total bill: 17.795


# find standard deviasion and variance of tip

In [20]:
print("Tip standard deviation:", tip_array.std())
print("Tip variance:", tip_array.var())

Tip standard deviation: 1.3807999538298954
Tip variance: 1.9066085124966412


# find log values of tip

In [21]:
print(np.log(tip_array))

[0.00995033 0.5068176  1.25276297 1.19694819 1.28370777 1.54968791
 0.69314718 1.137833   0.67294447 1.17248214 0.53649337 1.60943791
 0.45107562 1.09861229 1.10525683 1.36609165 0.51282363 1.31103188
 1.25276297 1.20896035 1.40609699 1.01160091 0.80200159 2.0255132
 1.1568812  0.85015093 0.69314718 0.69314718 1.45861502 1.09861229
 0.37156356 0.91629073 1.09861229 0.89608802 1.18478998 1.28093385
 0.69314718 1.12167756 0.83724752 1.60943791 0.80647587 0.93216408
 1.11841492 0.27763174 1.7227666  1.09861229 1.60943791 1.79175947
 0.71783979 1.09861229 0.91629073 0.95551145 1.64865863 0.44468582
 1.46787435 1.25561604 1.09861229 0.40546511 0.56531381 1.90657514
 1.16627094 0.69314718 0.68309684 1.32441896 0.97077892 1.14740245
 0.90421815 0.         0.69813472 0.73716407 0.67803354 1.09861229
 1.1442228  1.60943791 0.78845736 0.22314355 1.1249296  1.38629436
 1.09861229 0.99694863 1.09861229 1.22377543 0.60431597 1.60943791
 0.70803579 1.64287269 0.69314718 1.38629436 1.76644166 1.09861

# apply round, floor and ceil operation on tip array

In [22]:
print("Round:", np.round(tip_array))
print("Floor:", np.floor(tip_array))
print("Ceil:", np.ceil(tip_array))

Round: [ 1.  2.  4.  3.  4.  5.  2.  3.  2.  3.  2.  5.  2.  3.  3.  4.  2.  4.
  4.  3.  4.  3.  2.  8.  3.  2.  2.  2.  4.  3.  1.  2.  3.  2.  3.  4.
  2.  3.  2.  5.  2.  3.  3.  1.  6.  3.  5.  6.  2.  3.  2.  3.  5.  2.
  4.  4.  3.  2.  2.  7.  3.  2.  2.  4.  3.  3.  2.  1.  2.  2.  2.  3.
  3.  5.  2.  1.  3.  4.  3.  3.  3.  3.  2.  5.  2.  5.  2.  4.  6.  3.
  3.  4.  1.  4.  3.  5.  4.  2.  3.  2.  2.  3.  2.  3.  4.  2.  4.  4.
  4.  4.  3.  1.  4.  3.  4.  4.  5.  2.  2.  3.  2.  2.  2.  2.  3.  4.
  1.  2.  2.  2.  2.  3.  2.  2.  3.  1.  2.  2.  2.  3.  4.  7.  5.  5.
  2.  2.  1.  2.  2.  2.  2.  2.  3.  2.  2.  5.  5.  4.  3.  2.  4.  2.
  2.  2.  3.  3.  2.  4.  2.  2. 10.  3.  5.  3.  4.  3.  2.  2.  4.  4.
  4.  6.  4.  6.  3.  5.  4.  2.  4.  4.  2.  4.  3.  2.  4.  1.  2.  5.
  2.  2.  4.  2.  2.  2.  4.  3.  3.  3.  2.  2.  2.  5.  9.  2.  6.  1.
  3.  2.  1.  3.  2.  3.  2.  3.  2.  2.  2.  3.  3.  3.  2.  3.  3.  1.
  3.  1.  1.  1.  5.  6.  2.  2.  2.  3.]
Fl

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [23]:

print(one_d[0])
print(one_d[-1])
print(one_d[1:3])
print(one_d[:2])
print(one_d[::2])


print(two_d[0, 0])
print(two_d[1, 2])
print(two_d[0, :])
print(two_d[:, 1])
print(two_d[:, 1:3])

print(three_d[0, 0, 0])
print(three_d[1, 1, 1])
print(three_d[0, :, :])
print(three_d[:, 1, :])
print(three_d[:, :, 0])

1
4
[2 3]
[1 2]
[1 3]
1
7
[1 2 3 4]
[2 6]
[[2 3]
 [6 7]]
1
11
[[1 2 3]
 [4 5 6]]
[[ 4  5  6]
 [10 11 12]]
[[ 1  4]
 [ 7 10]]


# stacking and spliting

In [24]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

In [18]:
horizontal_array = np.hstack((d, e))
vertical_array = np.vstack((d, e))

print("Horizontal stack:")
print(horizontal_array)

print("Vertical stack:")
print(vertical_array)

Horizontal stack:
[[ 0  1  2  3  4  5  6  7  8 28 29 30 31 32 33 34 35 36]
 [ 9 10 11 12 13 14 15 16 17 37 38 39 40 41 42 43 44 45]
 [18 19 20 21 22 23 24 25 26 46 47 48 49 50 51 52 53 54]]
Vertical stack:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]


# use hsplit() and vsplit()

In [19]:
horizontal_split = np.hsplit(d, 3)
vertical_split = np.vsplit(d, 3)

print("Horizontal split:")
for part in horizontal_split:
    print(part)

print("Vertical split:")
for part in vertical_split:
    print(part)

Horizontal split:
[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]
Vertical split:
[[0 1 2 3 4 5 6 7 8]]
[[ 9 10 11 12 13 14 15 16 17]]
[[18 19 20 21 22 23 24 25 26]]
